name = "FeedbackParticleFilters"
uuid = "f4440bb6-80da-11e9-1db0-85cc1897f664"
authors = ["Simone Carlo Surace <simsurace@gmx.net>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
